name: Update Blog Posts in README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch blog posts
        run: |
          curl -s -X POST https://gql.hashnode.com \
          -H "Content-Type: application/json" \
          -d '{
            "query": "query { publication(host: \"iamgovinda.hashnode.dev\") { posts(first: 2) { edges { node { title slug } } } }"
          }' > response.json

      - name: Extract and format blog list
        id: bloglist
        run: |
          blog_list=$(jq -r '.data.publication.posts.edges[] | "- [\(.node.title)](https://iamgovinda.hashnode.dev/\(.node.slug))"' response.json)
          {
            echo "BLOG_LIST<<EOF"
            echo "$blog_list"
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Inject blog list into README
        run: |
          start="<!-- BLOG-POST-LIST:START -->"
          end="<!-- BLOG-POST-LIST:END -->"
          # Escape special characters
          escaped_blog_list=$(echo "$BLOG_LIST" | sed -e 's/[\/&]/\\&/g')
          # Use awk for safer multi-line replacement
          awk -v start="$start" -v end="$end" -v content="$escaped_blog_list" '
            BEGIN { in_block = 0 }
            $0 ~ start { in_block = 1; print; next }
            $0 ~ end { in_block = 0; print content; print; next }
            in_block == 0 { print }
          ' README.md > README.md.tmp && mv README.md.tmp README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update blog list in README" || echo "No changes to commit"
          git push